### PR TITLE
fix: update swatch-renderer-mixin.js

### PR DESCRIPTION
**Pull request by Amadeco**
I replaced all .data() call by attr()
source "jQuery .data() does not work, but .attr() does" (https://stackoverflow.com/questions/8707226/jquery-data-does-not-work-but-attr-does)

Also, when we calling AJAX we need to call again all events for this particular item if not it is not working.
I tried to improve js standard compared to magento code standard.

### CODE REVIEW

**Comment by dmatthew** [comment]
Are you actually seeing any errors with the current code? I'm testing with Magento 2.3.5 and its working fine.

**Comment by Amadeco** [comment]
Morning @dmatthew,

It simply doesn't work on Magento 2.3.5 and with Firefox browser 76.0.1.

Could you give it a try on your environment ?

When I were debugging
`mainImage.data('hover-image')`
return nothing
with this code, it returns the correct data.

**Comment by dmatthew** [comment]
I tested on Firefox 76.0 on Mac using Magento 2.3.5 with no other custom modules installed and it works fine. Do you have a publicly accessible website I can test it on showing that it's not working? 

Also, you say `mainImage.data('hover-image')` returns nothing. Are you referring to [this line](https://github.com/dmatthew/magento2-hover-image/blob/1.1.0/view/frontend/web/js/swatch-renderer-mixin.js#L17) in the code? When the page first loads that will always be empty. It will get the correct image [her](https://github.com/dmatthew/magento2-hover-image/blob/1.1.0/view/frontend/web/js/swatch-renderer-mixin.js#L18-L20).

**Comment by Amadeco** [comment]
> I tested on Firefox 76.0 on Mac using Magento 2.3.5 with no other custom modules installed and it works fine. Do you have a publicly accessible website I can test it on showing that it's not working?
> 
> Also, you say `mainImage.data('hover-image')` returns nothing. Are you referring to [this line](https://github.com/dmatthew/magento2-hover-image/blob/1.1.0/view/frontend/web/js/swatch-renderer-mixin.js#L17) in the code? When the page first loads that will always be empty. It will get the correct image [her](https://github.com/dmatthew/magento2-hover-image/blob/1.1.0/view/frontend/web/js/swatch-renderer-mixin.js#L18-L20).

Morning @dmatthew ,

I did a mistake with my review, it was due to a conflict with a module.
What a lost of time.

Ilan Parmentier

**Pull request closed without merging**
